In [1]:
import tensorflow_hub as hub
import tensorflow as tf
import PIL
import PIL.Image
import numpy as np
import matplotlib.pyplot as plt

In [2]:
hub_model = hub.load('https://tfhub.dev/google/magenta/arbitrary-image-stylization-v1-256/2')


In [7]:
house=PIL.Image.open("me.jpg")
starry=PIL.Image.open("cubism2.jpg")



In [4]:
def load_img(path_to_img):
    max_dim = 512
    img = tf.io.read_file(path_to_img)
    img = tf.image.decode_image(img, channels=3) # 0-255
    img = tf.image.convert_image_dtype(img, tf.float32) # 0-1

    shape = tf.cast(tf.shape(img)[:-1], tf.float32)
    long_dim = max(shape)
    scale = max_dim / long_dim

    new_shape = tf.cast(shape * scale, tf.int32)

    img = tf.image.resize(img, new_shape)
    img = img[tf.newaxis, :]
    return img

In [5]:
def load_img1(img):
    max_dim = 512
# img = tf.io.read_file("house.jpg")
# img = tf.image.decode_image(img, channels=3)

    
    img = tf.image.convert_image_dtype(img, tf.float32)


    shape = tf.cast(tf.shape(img)[:-1], tf.float32)
    long_dim = max(shape)
    scale = max_dim / long_dim

    new_shape = tf.cast(shape * scale, tf.int32)

    img = tf.image.resize(img, new_shape)
    img = img[tf.newaxis, :]
    return img

In [6]:
import cv2
cap = cv2.VideoCapture(0)

cap.set(3,640)
cap.set(4,480)


style = tf.constant(load_img("house.jpg"))
print(style)
preprocess_styel = starry

while True:
    break
    sucess,img = cap.read() #255 black    
    preprocess_img = load_img1(img) # 1 black

    stylized_image = hub_model(preprocess_img, style)[0]
    cv2.imshow("1",img)
    cv2.imshow("",cv2.cvtColor(stylized_image[0].numpy(), cv2.COLOR_BGR2RGB))
    if cv2.waitKey(1) == ord('1'):
        print("Cubism")
        style = tf.constant(load_img("cubism2.jpg"))
    if cv2.waitKey(1) == ord('2'):
        print("Starry Night")
        style = tf.constant(load_img("starry.jpg"))
    if cv2.waitKey(1) == ord('3'):
        print("Fire")
        style = tf.constant(load_img("fire.jpg"))
        
        
        
        
    if cv2.waitKey(1) and 0xff == ord("w"):
        break

tf.Tensor(
[[[[0.43137258 0.49411768 0.62352943]
   [0.43137258 0.49411768 0.62352943]
   [0.43137258 0.49411768 0.62352943]
   ...
   [0.41960788 0.48235297 0.6117647 ]
   [0.41960788 0.48235297 0.6117647 ]
   [0.41960788 0.48235297 0.6117647 ]]

  [[0.43226758 0.49501267 0.6244244 ]
   [0.43226758 0.49501267 0.6244244 ]
   [0.43226758 0.49501267 0.6244244 ]
   ...
   [0.42352945 0.48627454 0.6156863 ]
   [0.42352945 0.48627454 0.6156863 ]
   [0.42352945 0.48627454 0.6156863 ]]

  [[0.43547863 0.49822372 0.6276355 ]
   [0.43547863 0.49822372 0.6276355 ]
   [0.43547863 0.49822372 0.6276355 ]
   ...
   [0.427451   0.4901961  0.61960787]
   [0.427451   0.4901961  0.61960787]
   [0.427451   0.4901961  0.61960787]]

  ...

  [[0.59197235 0.6076586  0.6507959 ]
   [0.5834329  0.5991192  0.64225644]
   [0.5802001  0.59588635 0.6390236 ]
   ...
   [0.25084326 0.21947071 0.07437266]
   [0.25247547 0.22110294 0.06844793]
   [0.27776855 0.22678816 0.09345482]]

  [[0.5836079  0.5992942  0.642431